"use client";

import Link from "next/link";
import { useI18n } from "@/lib/i18n/context";
import { StoryPageShell, StoryCard } from "@/components/StoryPageShell";
import { Reveal } from "@/components/Reveal";
import { PascalmodViewer } from "@/components/PascalmodViewer";
import { PascalmodCarryDemo } from "@/components/PascalmodCarryDemo";
import type { Locale } from "@/lib/i18n/types";
import type { StoryPage } from "@/lib/i18n/stories";

const ACCENT = "text-signal-amber";

// --------------------------------------------------------------------------
// Pascal's triangle (mod n) — long-form story page. The canonical hero
// (pretitle/title/tagline/intro/cta) lives inside RICH_STORY[locale].page so
// the page module owns the whole copy; we inject sections:[] at the call
// site since the shell never reads that field.
// --------------------------------------------------------------------------

type RichStory = {
  page: Omit<StoryPage, "sections">;
  encounter: {
    pretitle: string;
    title: string;
    cards: Array<{ label: string; title: string; body: string }>;
    tryIt: string;
  };
  sections: Array<{ pretitle: string; title: string; body: string }>;
  viewer: {
    caption: string;
    modulusLabel: string;
    rowsLabel: string;
    primesOnlyLabel: string;
    includeCompositesLabel: string;
    pretitle: string;
    title: string;
    body: string;
  };
  carry: {
    caption: string;
    nLabel: string;
    kLabel: string;
    pLabel: string;
    resultLabel: string;
    carryLabel: string;
    noCarryLabel: string;
    hint: string;
    pretitle: string;
    title: string;
    body: string;
  };
  dimensionLabel: string;
  dimensionNote: string;
  closingPretitle: string;
  closingTitle: string;
  closingBody: string;
  ctaLabel: string;
};

const en: RichStory = {
  page: {
    pretitle: "Topic · Geometry",
    title: "Pascal's Triangle (mod n)",
    tagline: "Colour by divisibility — a fractal falls out.",
    intro:
      "Pascal's triangle is the lookup table for the binomial coefficients C(n, k). Each number is just the sum of the two above it. Reduce every entry modulo a prime and the resulting colour pattern is a perfect, infinite fractal. The reason hides inside base-p arithmetic.",
    ctaInteractive: "→ Open the Explorer",
  },
  encounter: {
    pretitle: "First encounter",
    title: "Write a triangle of numbers. Colour the odd ones. Watch a fractal arrive.",
    cards: [
      {
        label: "01",
        title: "The big idea",
        body: "Stack the binomial coefficients C(n, k) into a triangle: 1 on top, then 1 1, then 1 2 1, and so on, each entry being the sum of the two above. Now keep only the remainder modulo a prime p. The picture that emerges is fractal, exact, and infinite.",
      },
      {
        label: "02",
        title: "A concrete example",
        body: "Take p = 2. Mark every odd entry, leave every even one blank. Step back. You are looking at the Sierpiński triangle — not an approximation, the real thing, generated by pure counting. Three self-similar copies at every scale, forever.",
      },
      {
        label: "03",
        title: "Why it matters",
        body: "Kummer proved in 1852 that the power of p dividing C(n, k) equals the number of carries when k + (n−k) is added in base p. So the fractal is a picture of when base-p addition is clean — geometry hiding inside arithmetic.",
      },
    ],
    tryIt:
      "Below: slide the modulus and the row count, then watch a single column of additions decide every colour.",
  },
  sections: [
    {
      pretitle: "Section 01 · The triangle itself",
      title: "C(n, k) — the simplest counting rule on Earth",
      body: "Write 1 at the apex. Underneath, every entry is the sum of the two above it. The rows you get — 1 · 1 1 · 1 2 1 · 1 3 3 1 · 1 4 6 4 1 — are the binomial coefficients C(n, k), counting how many ways to choose k items from n. They are also the only ingredient needed to make a fractal.",
    },
    {
      pretitle: "Section 02 · Colour by remainder",
      title: "Mod 2 is Sierpiński, exactly",
      body: "Replace each entry with its remainder modulo 2 and colour only the odd cells. Step back and the picture is the Sierpiński triangle — the exact self-similar gasket, all the way down. Any block of 2^k rows is three copies of the 2^(k−1) block arranged in a triangle, with the centre hollow.",
    },
    {
      pretitle: "Section 03 · Kummer's theorem (1852)",
      title: "Divisibility = number of carries",
      body: "Why does mod p factor so cleanly? Kummer's theorem says the highest power of p dividing C(n, k) is the number of carries when k and (n − k) are added in base p. So C(n, k) ≢ 0 mod p precisely when no carry happens — when every base-p digit of k stays ≤ the corresponding digit of n. The fractal is a portrait of carry-free addition.",
    },
    {
      pretitle: "Section 04 · Other primes, other gaskets",
      title: "Mod 3, mod 5, mod 7 — each its own self-similar sieve",
      body: "Switch p to 3 and the same rule produces a triangle of three-by-three copies; p = 5 gives a fifteen-piece micro-tile; p = 7 a twenty-eight-piece one. Lucas' theorem (1878) makes it explicit: C(n, k) mod p factors into the product of C(nᵢ, kᵢ) mod p over base-p digits. Different prime, different fractal — same machinery.",
    },
    {
      pretitle: "Section 05 · Hausdorff dimensions",
      title: "log((p+1)p/2) / log p, climbing toward 2",
      body: "The mod-p gasket has Hausdorff dimension log((p+1)p/2) / log p. For p = 2 it equals log 3 / log 2 ≈ 1.585; for p = 3 about 1.631; for p = 7 already 1.771. As p grows the dimension creeps toward 2 — the triangle fills more and more of the plane, but never quite all of it.",
    },
    {
      pretitle: "Section 06 · Non-prime moduli",
      title: "Composite n: the fractal still exists, but blurred",
      body: "Reduce mod 6 and Kummer's clean carry count breaks: the prime-power structure tangles. The picture still self-similar overall — Chinese Remainder Theorem stacks the mod-2 and mod-3 patterns — but local symmetry frays. Stephen Wolfram catalogued these in NKS as nearest cellular-automaton kin to Pascal mod p.",
    },
  ],
  viewer: {
    caption: "Interactive · Pascal triangle mod p",
    modulusLabel: "Modulus p",
    rowsLabel: "Rows N",
    primesOnlyLabel: "Primes only",
    includeCompositesLabel: "Include composites",
    pretitle: "Interactive · the picture",
    title: "Slide the modulus, count the gasket",
    body: "Pick a prime and the rendering snaps to a clean fractal sieve; toggle in composites and the symmetry softens. Crank N up to 256 rows to see deeper self-similarity.",
  },
  carry: {
    caption: "Interactive · Kummer's carry counter",
    nLabel: "n",
    kLabel: "k",
    pLabel: "prime p",
    resultLabel: "Lucas value",
    carryLabel: "Carries (≥ 1 ⇒ divisible)",
    noCarryLabel: "Carries (0 ⇒ non-zero mod p)",
    hint: "Zero carries means C(n, k) is non-zero mod p — a coloured cell in the gasket. Any carry sends C(n, k) to 0 mod p — a blank cell.",
    pretitle: "Interactive · the rule behind the colour",
    title: "Add k + (n − k) in base p and watch a carry decide",
    body: "Type any n and k. Pick a prime. The viewer stacks the base-p digits of k and (n − k); columns that carry glow amber. Zero carries ⇒ the cell is coloured. One carry ⇒ the cell is blank.",
  },
  dimensionLabel: "Hausdorff dimension",
  dimensionNote:
    "Strictly between a curve (1) and a region (2). As p grows the gasket fills more — the limit is 2, never reached.",
  closingPretitle: "Take it further",
  closingTitle: "Open the Explorer.",
  closingBody:
    "The Explorer lets you push the row count to half a thousand, switch palettes per residue, and step through every prime modulus from 2 to 23.",
  ctaLabel: "→ Open the Explorer",
};

const de: RichStory = {
  page: {
    pretitle: "Thema · Geometrie",
    title: "Pascals Dreieck (mod n)",
    tagline: "Färbe nach Teilbarkeit — und ein Fraktal fällt heraus.",
    intro:
      "Pascals Dreieck ist die Nachschlagetabelle der Binomialkoeffizienten C(n, k). Jeder Eintrag ist nur die Summe der beiden darüber. Reduziere modulo einer Primzahl — und das Farbmuster, das übrig bleibt, ist ein perfektes, unendliches Fraktal. Der Grund versteckt sich in der p-adischen Arithmetik.",
    ctaInteractive: "→ Explorer öffnen",
  },
  encounter: {
    pretitle: "Erste Begegnung",
    title: "Schreib ein Zahlendreieck. Färbe die ungeraden Einträge. Sieh ein Fraktal entstehen.",
    cards: [
      {
        label: "01",
        title: "Die große Idee",
        body: "Stapel die Binomialkoeffizienten C(n, k) zu einem Dreieck: oben 1, dann 1 1, dann 1 2 1, und so weiter, jeder Eintrag die Summe der beiden darüber. Behalte nur den Rest modulo einer Primzahl p. Das Bild, das übrig bleibt, ist fraktal, exakt, unendlich.",
      },
      {
        label: "02",
        title: "Ein konkretes Beispiel",
        body: "Nimm p = 2. Markiere jeden ungeraden Eintrag, lass jeden geraden leer. Tritt zurück. Du siehst das Sierpiński-Dreieck — nicht eine Annäherung, das echte Ding, allein durch Zählen erzeugt. Drei selbstähnliche Kopien auf jeder Skala, für immer.",
      },
      {
        label: "03",
        title: "Warum es zählt",
        body: "Kummer bewies 1852, dass die Potenz von p, die C(n, k) teilt, gleich der Anzahl der Überträge bei der Addition k + (n−k) zur Basis p ist. Das Fraktal ist also ein Bild davon, wann p-adische Addition übertragsfrei ist — Geometrie versteckt in Arithmetik.",
      },
    ],
    tryIt:
      "Unten: schieb Modulus und Zeilenzahl, dann lass eine einzige Spalte Additionen jede Farbe entscheiden.",
  },
  sections: [
    {
      pretitle: "Abschnitt 01 · Das Dreieck selbst",
      title: "C(n, k) — die einfachste Zählregel der Welt",
      body: "Schreib 1 oben. Darunter ist jeder Eintrag die Summe der beiden darüber. Die Zeilen — 1 · 1 1 · 1 2 1 · 1 3 3 1 · 1 4 6 4 1 — sind die Binomialkoeffizienten C(n, k) und zählen, auf wie viele Arten man k Dinge aus n auswählt. Mehr braucht es nicht, um ein Fraktal zu bauen.",
    },
    {
      pretitle: "Abschnitt 02 · Färbe nach Rest",
      title: "Mod 2 ist Sierpiński, exakt",
      body: "Ersetz jeden Eintrag durch seinen Rest modulo 2 und färbe nur die ungeraden Zellen. Tritt zurück — und du siehst das Sierpiński-Dreieck, das exakte selbstähnliche Sieb, ganz nach unten. Jeder 2^k-Zeilen-Block ist drei Kopien des 2^(k−1)-Blocks in Dreiecksanordnung, mit hohler Mitte.",
    },
    {
      pretitle: "Abschnitt 03 · Kummers Satz (1852)",
      title: "Teilbarkeit = Anzahl der Überträge",
      body: "Warum spaltet sich mod p so sauber? Kummers Satz sagt: die höchste Potenz von p, die C(n, k) teilt, ist die Anzahl der Überträge bei der Addition k + (n − k) zur Basis p. Also C(n, k) ≢ 0 mod p genau dann, wenn kein Übertrag auftritt — wenn jede p-adische Ziffer von k ≤ der entsprechenden Ziffer von n bleibt. Das Fraktal porträtiert übertragsfreie Addition.",
    },
    {
      pretitle: "Abschnitt 04 · Andere Primzahlen, andere Sieben",
      title: "Mod 3, mod 5, mod 7 — je ein eigenes selbstähnliches Sieb",
      body: "Schalt p auf 3 und dieselbe Regel liefert ein Dreieck aus drei-mal-drei-Kopien; p = 5 ergibt eine fünfzehnteilige Mikrokachel; p = 7 eine mit achtundzwanzig Teilen. Der Satz von Lucas (1878) macht es explizit: C(n, k) mod p zerfällt in das Produkt der C(nᵢ, kᵢ) mod p über die p-adischen Ziffern. Andere Primzahl, anderes Fraktal — gleiches Räderwerk.",
    },
    {
      pretitle: "Abschnitt 05 · Hausdorff-Dimensionen",
      title: "log((p+1)p/2) / log p, gegen 2 strebend",
      body: "Das mod-p-Sieb hat Hausdorff-Dimension log((p+1)p/2) / log p. Für p = 2 ergibt das log 3 / log 2 ≈ 1,585; für p = 3 etwa 1,631; für p = 7 schon 1,771. Mit wachsendem p kriecht die Dimension gegen 2 — das Dreieck füllt mehr und mehr der Ebene, aber nie ganz.",
    },
    {
      pretitle: "Abschnitt 06 · Zusammengesetzte Modulen",
      title: "Nicht-Primes n: das Fraktal bleibt, verwischt",
      body: "Reduziere mod 6 und Kummers saubere Übertragszahl bricht: die Primzahlpotenz-Struktur verheddert sich. Das Bild bleibt insgesamt selbstähnlich — der Chinesische Restsatz stapelt mod 2 und mod 3 übereinander — aber lokale Symmetrie franst aus. Stephen Wolfram katalogisierte solche Bilder in NKS als nächste Zellulär-Automaten-Verwandte von Pascal mod p.",
    },
  ],
  viewer: {
    caption: "Interaktiv · Pascal-Dreieck mod p",
    modulusLabel: "Modulus p",
    rowsLabel: "Zeilen N",
    primesOnlyLabel: "Nur Primzahlen",
    includeCompositesLabel: "Zusammengesetzte einschließen",
    pretitle: "Interaktiv · das Bild",
    title: "Schieb den Modulus, zähl das Sieb",
    body: "Wähl eine Primzahl und das Bild rastet als sauberes fraktales Sieb ein; schalt zusammengesetzte hinzu und die Symmetrie weicht auf. Dreh N auf 256, um tiefere Selbstähnlichkeit zu sehen.",
  },
  carry: {
    caption: "Interaktiv · Kummers Übertrags-Zähler",
    nLabel: "n",
    kLabel: "k",
    pLabel: "Primzahl p",
    resultLabel: "Lucas-Wert",
    carryLabel: "Überträge (≥ 1 ⇒ teilbar)",
    noCarryLabel: "Überträge (0 ⇒ nicht-null mod p)",
    hint: "Null Überträge heißt C(n, k) ist nicht null mod p — eine gefärbte Zelle im Sieb. Jeder Übertrag schickt C(n, k) auf 0 mod p — eine leere Zelle.",
    pretitle: "Interaktiv · die Regel hinter der Farbe",
    title: "Addiere k + (n − k) zur Basis p, sieh den Übertrag entscheiden",
    body: "Tipp ein n und ein k ein. Wähl eine Primzahl. Die Ansicht stapelt die p-adischen Ziffern von k und (n − k); Spalten mit Übertrag glühen amber. Null Überträge ⇒ Zelle gefärbt. Ein Übertrag ⇒ Zelle leer.",
  },
  dimensionLabel: "Hausdorff-Dimension",
  dimensionNote:
    "Streng zwischen Kurve (1) und Fläche (2). Mit wachsendem p füllt das Sieb mehr — Grenzwert 2, nie erreicht.",
  closingPretitle: "Geh weiter",
  closingTitle: "Öffne den Explorer.",
  closingBody:
    "Der Explorer lässt dich die Zeilenzahl bis fünfhundert treiben, die Palette pro Rest umschalten und jede Primzahl von 2 bis 23 durchspielen.",
  ctaLabel: "→ Explorer öffnen",
};

const es: RichStory = {
  page: {
    pretitle: "Tema · Geometría",
    title: "El triángulo de Pascal (mod n)",
    tagline: "Colorea por divisibilidad — y sale un fractal.",
    intro:
      "El triángulo de Pascal es la tabla de los coeficientes binomiales C(n, k). Cada entrada es la suma de las dos de arriba. Reduce módulo un primo y el patrón de color que queda es un fractal perfecto e infinito. La razón se esconde en la aritmética en base p.",
    ctaInteractive: "→ Abrir el Explorador",
  },
  encounter: {
    pretitle: "Primer encuentro",
    title: "Escribe un triángulo de números. Colorea los impares. Mira aparecer un fractal.",
    cards: [
      {
        label: "01",
        title: "La gran idea",
        body: "Apila los coeficientes binomiales C(n, k) en un triángulo: 1 arriba, luego 1 1, luego 1 2 1, y así, cada entrada es la suma de las dos de arriba. Quédate solo con el resto módulo un primo p. La imagen que queda es fractal, exacta, infinita.",
      },
      {
        label: "02",
        title: "Un ejemplo concreto",
        body: "Toma p = 2. Marca cada entrada impar, deja en blanco las pares. Da un paso atrás. Estás mirando el triángulo de Sierpiński — no una aproximación, el de verdad, generado por puro contar. Tres copias autosemejantes en cada escala, para siempre.",
      },
      {
        label: "03",
        title: "Por qué importa",
        body: "Kummer demostró en 1852 que la potencia de p que divide a C(n, k) es el número de acarreos al sumar k + (n−k) en base p. Así que el fractal es un retrato de cuándo la suma en base p es limpia — geometría escondida en aritmética.",
      },
    ],
    tryIt:
      "Abajo: desliza el módulo y el número de filas, y deja que una sola columna de sumas decida cada color.",
  },
  sections: [
    {
      pretitle: "Sección 01 · El triángulo mismo",
      title: "C(n, k) — la regla de conteo más simple",
      body: "Escribe 1 en la cima. Debajo, cada entrada es la suma de las dos de arriba. Las filas — 1 · 1 1 · 1 2 1 · 1 3 3 1 · 1 4 6 4 1 — son los coeficientes binomiales C(n, k), que cuentan de cuántas maneras se eligen k objetos de n. No hace falta más para fabricar un fractal.",
    },
    {
      pretitle: "Sección 02 · Colorea por resto",
      title: "Módulo 2 es Sierpiński, exactamente",
      body: "Sustituye cada entrada por su resto módulo 2 y colorea solo las impares. Da un paso atrás y la imagen es el triángulo de Sierpiński — el tamiz autosemejante exacto, hasta el fondo. Cualquier bloque de 2^k filas son tres copias del bloque 2^(k−1) en disposición triangular, con el centro vacío.",
    },
    {
      pretitle: "Sección 03 · El teorema de Kummer (1852)",
      title: "Divisibilidad = número de acarreos",
      body: "¿Por qué módulo p se factoriza tan limpio? El teorema de Kummer dice que la mayor potencia de p que divide a C(n, k) es el número de acarreos al sumar k y (n − k) en base p. Así C(n, k) ≢ 0 mod p justo cuando no hay acarreo — cuando cada dígito en base p de k es ≤ al dígito correspondiente de n. El fractal es un retrato de la suma sin acarreo.",
    },
    {
      pretitle: "Sección 04 · Otros primos, otros tamices",
      title: "Mod 3, mod 5, mod 7 — cada uno su propio tamiz autosemejante",
      body: "Cambia p a 3 y la misma regla da un triángulo de copias tres-por-tres; p = 5 da una microbaldosa de quince piezas; p = 7 una de veintiocho. El teorema de Lucas (1878) lo hace explícito: C(n, k) mod p se factoriza como producto de C(nᵢ, kᵢ) mod p sobre los dígitos en base p. Otro primo, otro fractal — mismo engranaje.",
    },
    {
      pretitle: "Sección 05 · Dimensiones de Hausdorff",
      title: "log((p+1)p/2) / log p, trepando hacia 2",
      body: "El tamiz mod p tiene dimensión de Hausdorff log((p+1)p/2) / log p. Para p = 2 da log 3 / log 2 ≈ 1,585; para p = 3 cerca de 1,631; para p = 7 ya 1,771. Al crecer p, la dimensión sube hacia 2 — el triángulo cubre cada vez más plano, pero nunca todo.",
    },
    {
      pretitle: "Sección 06 · Módulos no primos",
      title: "n compuesto: el fractal sigue, pero borroso",
      body: "Reduce mod 6 y el conteo limpio de Kummer se rompe: la estructura de potencias primas se enreda. La imagen sigue autosemejante en grande — el teorema chino del resto apila los patrones mod 2 y mod 3 — pero la simetría local se deshilacha. Stephen Wolfram catalogó estos en NKS como autómatas celulares más cercanos a Pascal mod p.",
    },
  ],
  viewer: {
    caption: "Interactivo · triángulo de Pascal mod p",
    modulusLabel: "Módulo p",
    rowsLabel: "Filas N",
    primesOnlyLabel: "Solo primos",
    includeCompositesLabel: "Incluir compuestos",
    pretitle: "Interactivo · la imagen",
    title: "Mueve el módulo, cuenta el tamiz",
    body: "Elige un primo y el render encaja en un tamiz fractal limpio; activa compuestos y la simetría se reblandece. Sube N a 256 filas para ver autosemejanza más profunda.",
  },
  carry: {
    caption: "Interactivo · contador de acarreos de Kummer",
    nLabel: "n",
    kLabel: "k",
    pLabel: "primo p",
    resultLabel: "Valor de Lucas",
    carryLabel: "Acarreos (≥ 1 ⇒ divisible)",
    noCarryLabel: "Acarreos (0 ⇒ no nulo mod p)",
    hint: "Cero acarreos significa que C(n, k) es no nulo mod p — una celda coloreada del tamiz. Cualquier acarreo manda C(n, k) a 0 mod p — celda en blanco.",
    pretitle: "Interactivo · la regla detrás del color",
    title: "Suma k + (n − k) en base p y mira decidir al acarreo",
    body: "Teclea cualquier n y k. Elige un primo. La vista apila los dígitos en base p de k y (n − k); las columnas que acarrean brillan en ámbar. Cero acarreos ⇒ celda coloreada. Un acarreo ⇒ celda vacía.",
  },
  dimensionLabel: "Dimensión de Hausdorff",
  dimensionNote:
    "Estrictamente entre una curva (1) y una región (2). Al crecer p el tamiz se llena más — el límite es 2, nunca alcanzado.",
  closingPretitle: "Ve más lejos",
  closingTitle: "Abre el Explorador.",
  closingBody:
    "El Explorador te deja empujar las filas hasta medio millar, alternar paletas por residuo, y recorrer cada primo de 2 a 23.",
  ctaLabel: "→ Abrir el Explorador",
};

const fr: RichStory = {
  page: {
    pretitle: "Sujet · Géométrie",
    title: "Le triangle de Pascal (mod n)",
    tagline: "Colore selon la divisibilité — un fractal apparaît.",
    intro:
      "Le triangle de Pascal est la table des coefficients binomiaux C(n, k). Chaque entrée est la somme des deux du dessus. Réduis modulo un nombre premier et le motif coloré qui reste est une fractale parfaite et infinie. La raison se cache dans l'arithmétique en base p.",
    ctaInteractive: "→ Ouvrir l'Explorateur",
  },
  encounter: {
    pretitle: "Première rencontre",
    title: "Écris un triangle de nombres. Colorie les impairs. Regarde une fractale arriver.",
    cards: [
      {
        label: "01",
        title: "L'idée centrale",
        body: "Empile les coefficients binomiaux C(n, k) en triangle : 1 au sommet, puis 1 1, puis 1 2 1, et ainsi de suite, chaque entrée étant la somme des deux du dessus. Ne garde que le reste modulo un premier p. L'image qui reste est fractale, exacte, infinie.",
      },
      {
        label: "02",
        title: "Un exemple concret",
        body: "Prends p = 2. Marque chaque entrée impaire, laisse les paires en blanc. Recule. Tu regardes le triangle de Sierpiński — pas une approximation, le vrai, engendré par pur comptage. Trois copies autosemblables à chaque échelle, pour toujours.",
      },
      {
        label: "03",
        title: "Pourquoi ça compte",
        body: "Kummer a prouvé en 1852 que la puissance de p divisant C(n, k) égale le nombre de retenues lors de l'addition k + (n−k) en base p. Donc la fractale est un portrait de quand l'addition en base p est sans retenue — géométrie cachée dans l'arithmétique.",
      },
    ],
    tryIt:
      "Ci-dessous : fais glisser le module et le nombre de lignes, puis laisse une seule colonne d'additions décider chaque couleur.",
  },
  sections: [
    {
      pretitle: "Section 01 · Le triangle lui-même",
      title: "C(n, k) — la règle de comptage la plus simple",
      body: "Écris 1 au sommet. En dessous, chaque entrée est la somme des deux du dessus. Les lignes — 1 · 1 1 · 1 2 1 · 1 3 3 1 · 1 4 6 4 1 — sont les coefficients binomiaux C(n, k), qui comptent de combien de façons choisir k objets parmi n. C'est tout ce qu'il faut pour fabriquer une fractale.",
    },
    {
      pretitle: "Section 02 · Colorier par reste",
      title: "Mod 2 est Sierpiński, exactement",
      body: "Remplace chaque entrée par son reste modulo 2 et ne colorie que les cases impaires. Recule, et l'image est le triangle de Sierpiński — le tamis autosemblable exact, jusqu'en bas. Tout bloc de 2^k lignes est trois copies du bloc 2^(k−1) en triangle, centre creux.",
    },
    {
      pretitle: "Section 03 · Le théorème de Kummer (1852)",
      title: "Divisibilité = nombre de retenues",
      body: "Pourquoi mod p se factorise si proprement ? Kummer affirme : la plus grande puissance de p qui divise C(n, k) est le nombre de retenues lors de l'addition k + (n − k) en base p. Donc C(n, k) ≢ 0 mod p exactement quand aucune retenue n'a lieu — quand chaque chiffre en base p de k reste ≤ au chiffre correspondant de n. La fractale est le portrait de l'addition sans retenue.",
    },
    {
      pretitle: "Section 04 · Autres premiers, autres tamis",
      title: "Mod 3, mod 5, mod 7 — chacun son tamis autosemblable",
      body: "Change p en 3 et la même règle donne un triangle de copies trois-par-trois ; p = 5 donne une micro-tuile en quinze morceaux ; p = 7 une en vingt-huit. Le théorème de Lucas (1878) le rend explicite : C(n, k) mod p se factorise en produit des C(nᵢ, kᵢ) mod p sur les chiffres en base p. Autre premier, autre fractale — même mécanique.",
    },
    {
      pretitle: "Section 05 · Dimensions de Hausdorff",
      title: "log((p+1)p/2) / log p, qui grimpe vers 2",
      body: "Le tamis mod p a pour dimension de Hausdorff log((p+1)p/2) / log p. Pour p = 2 cela vaut log 3 / log 2 ≈ 1,585 ; pour p = 3 environ 1,631 ; pour p = 7 déjà 1,771. Quand p grandit, la dimension monte vers 2 — le triangle remplit de plus en plus le plan, mais jamais tout.",
    },
    {
      pretitle: "Section 06 · Modules non premiers",
      title: "n composé : la fractale demeure, mais floue",
      body: "Réduis mod 6 et le décompte propre de Kummer se brise : la structure de puissances premières s'emmêle. L'image reste autosemblable en gros — le théorème chinois des restes empile les motifs mod 2 et mod 3 — mais la symétrie locale s'effiloche. Stephen Wolfram a catalogué ces images dans NKS comme automates cellulaires les plus proches de Pascal mod p.",
    },
  ],
  viewer: {
    caption: "Interactif · triangle de Pascal mod p",
    modulusLabel: "Module p",
    rowsLabel: "Lignes N",
    primesOnlyLabel: "Premiers seuls",
    includeCompositesLabel: "Inclure les composés",
    pretitle: "Interactif · l'image",
    title: "Fais glisser le module, compte le tamis",
    body: "Choisis un premier et le rendu se cale sur un tamis fractal net ; active les composés et la symétrie s'amollit. Pousse N à 256 lignes pour voir une autosimilarité plus profonde.",
  },
  carry: {
    caption: "Interactif · compteur de retenues de Kummer",
    nLabel: "n",
    kLabel: "k",
    pLabel: "premier p",
    resultLabel: "Valeur de Lucas",
    carryLabel: "Retenues (≥ 1 ⇒ divisible)",
    noCarryLabel: "Retenues (0 ⇒ non nul mod p)",
    hint: "Zéro retenue signifie que C(n, k) est non nul mod p — une case colorée du tamis. La moindre retenue envoie C(n, k) à 0 mod p — case vide.",
    pretitle: "Interactif · la règle derrière la couleur",
    title: "Additionne k + (n − k) en base p et regarde la retenue décider",
    body: "Tape n et k. Choisis un premier. La vue empile les chiffres en base p de k et (n − k) ; les colonnes qui retiennent s'illuminent en ambre. Zéro retenue ⇒ case colorée. Une retenue ⇒ case vide.",
  },
  dimensionLabel: "Dimension de Hausdorff",
  dimensionNote:
    "Strictement entre une courbe (1) et une région (2). Quand p croît, le tamis se remplit davantage — limite 2, jamais atteinte.",
  closingPretitle: "Aller plus loin",
  closingTitle: "Ouvre l'Explorateur.",
  closingBody:
    "L'Explorateur te laisse pousser le nombre de lignes jusqu'à cinq cents, changer les palettes par résidu et parcourir chaque premier de 2 à 23.",
  ctaLabel: "→ Ouvrir l'Explorateur",
};

const it: RichStory = {
  page: {
    pretitle: "Tema · Geometria",
    title: "Il triangolo di Pascal (mod n)",
    tagline: "Colora per divisibilità — esce un frattale.",
    intro:
      "Il triangolo di Pascal è la tabella dei coefficienti binomiali C(n, k). Ogni voce è la somma delle due sopra. Riduci modulo un primo e il motivo colorato che resta è un frattale perfetto e infinito. La ragione si nasconde nell'aritmetica in base p.",
    ctaInteractive: "→ Apri l'Esploratore",
  },
  encounter: {
    pretitle: "Primo incontro",
    title: "Scrivi un triangolo di numeri. Colora i dispari. Guarda arrivare un frattale.",
    cards: [
      {
        label: "01",
        title: "L'idea centrale",
        body: "Impila i coefficienti binomiali C(n, k) in un triangolo: 1 in cima, poi 1 1, poi 1 2 1, e così via, ogni voce è la somma delle due sopra. Tieni solo il resto modulo un primo p. L'immagine che resta è frattale, esatta, infinita.",
      },
      {
        label: "02",
        title: "Un esempio concreto",
        body: "Prendi p = 2. Segna ogni voce dispari, lascia in bianco le pari. Fai un passo indietro. Stai guardando il triangolo di Sierpiński — non un'approssimazione, quello vero, generato dal puro contare. Tre copie autosimili a ogni scala, per sempre.",
      },
      {
        label: "03",
        title: "Perché conta",
        body: "Kummer dimostrò nel 1852 che la potenza di p che divide C(n, k) è il numero di riporti quando si somma k + (n−k) in base p. Quindi il frattale è un ritratto di quando la somma in base p è senza riporti — geometria nascosta nell'aritmetica.",
      },
    ],
    tryIt:
      "Sotto: muovi il modulo e il numero di righe, e lascia che una sola colonna di addizioni decida ogni colore.",
  },
  sections: [
    {
      pretitle: "Sezione 01 · Il triangolo stesso",
      title: "C(n, k) — la regola di conteggio più semplice",
      body: "Scrivi 1 in alto. Sotto, ogni voce è la somma delle due sopra. Le righe — 1 · 1 1 · 1 2 1 · 1 3 3 1 · 1 4 6 4 1 — sono i coefficienti binomiali C(n, k), che contano in quanti modi scegliere k oggetti da n. Non serve altro per costruire un frattale.",
    },
    {
      pretitle: "Sezione 02 · Colora per resto",
      title: "Mod 2 è Sierpiński, esattamente",
      body: "Sostituisci ogni voce col suo resto modulo 2 e colora solo le dispari. Fai un passo indietro e l'immagine è il triangolo di Sierpiński — il setaccio autosimile esatto, fino in fondo. Ogni blocco di 2^k righe è tre copie del blocco 2^(k−1) disposte in triangolo, con il centro vuoto.",
    },
    {
      pretitle: "Sezione 03 · Il teorema di Kummer (1852)",
      title: "Divisibilità = numero di riporti",
      body: "Perché mod p si fattorizza così pulito? Il teorema di Kummer dice che la massima potenza di p che divide C(n, k) è il numero di riporti quando si sommano k e (n − k) in base p. Quindi C(n, k) ≢ 0 mod p esattamente quando non c'è alcun riporto — quando ogni cifra in base p di k resta ≤ alla cifra corrispondente di n. Il frattale è il ritratto della somma senza riporto.",
    },
    {
      pretitle: "Sezione 04 · Altri primi, altri setacci",
      title: "Mod 3, mod 5, mod 7 — ciascuno il suo setaccio autosimile",
      body: "Cambia p in 3 e la stessa regola produce un triangolo di copie tre-per-tre; p = 5 dà una micro-mattonella da quindici pezzi; p = 7 una da ventotto. Il teorema di Lucas (1878) lo rende esplicito: C(n, k) mod p si fattorizza come prodotto di C(nᵢ, kᵢ) mod p sulle cifre in base p. Altro primo, altro frattale — stesso meccanismo.",
    },
    {
      pretitle: "Sezione 05 · Dimensioni di Hausdorff",
      title: "log((p+1)p/2) / log p, in salita verso 2",
      body: "Il setaccio mod p ha dimensione di Hausdorff log((p+1)p/2) / log p. Per p = 2 vale log 3 / log 2 ≈ 1,585; per p = 3 circa 1,631; per p = 7 già 1,771. Crescendo p, la dimensione tende a 2 — il triangolo riempie sempre più piano, ma mai tutto.",
    },
    {
      pretitle: "Sezione 06 · Moduli non primi",
      title: "n composto: il frattale resta, sfocato",
      body: "Riduci mod 6 e il conteggio pulito di Kummer si rompe: la struttura per potenze prime si ingarbuglia. L'immagine resta autosimile in grande — il teorema cinese del resto impila i pattern mod 2 e mod 3 — ma la simmetria locale si sfilaccia. Stephen Wolfram ha catalogato queste in NKS come gli automi cellulari più affini a Pascal mod p.",
    },
  ],
  viewer: {
    caption: "Interattivo · triangolo di Pascal mod p",
    modulusLabel: "Modulo p",
    rowsLabel: "Righe N",
    primesOnlyLabel: "Solo primi",
    includeCompositesLabel: "Includi compositi",
    pretitle: "Interattivo · l'immagine",
    title: "Muovi il modulo, conta il setaccio",
    body: "Scegli un primo e il rendering scatta su un setaccio frattale netto; attiva i compositi e la simmetria si ammorbidisce. Porta N a 256 righe per vedere autosimilarità più profonda.",
  },
  carry: {
    caption: "Interattivo · contatore di riporti di Kummer",
    nLabel: "n",
    kLabel: "k",
    pLabel: "primo p",
    resultLabel: "Valore di Lucas",
    carryLabel: "Riporti (≥ 1 ⇒ divisibile)",
    noCarryLabel: "Riporti (0 ⇒ non nullo mod p)",
    hint: "Zero riporti significa che C(n, k) è non nullo mod p — una cella colorata del setaccio. Qualsiasi riporto manda C(n, k) a 0 mod p — cella vuota.",
    pretitle: "Interattivo · la regola dietro al colore",
    title: "Somma k + (n − k) in base p e guarda decidere il riporto",
    body: "Digita n e k. Scegli un primo. La vista impila le cifre in base p di k e (n − k); le colonne che riportano brillano in ambra. Zero riporti ⇒ cella colorata. Un riporto ⇒ cella vuota.",
  },
  dimensionLabel: "Dimensione di Hausdorff",
  dimensionNote:
    "Strettamente tra curva (1) e regione (2). Al crescere di p il setaccio si riempie di più — limite 2, mai raggiunto.",
  closingPretitle: "Vai oltre",
  closingTitle: "Apri l'Esploratore.",
  closingBody:
    "L'Esploratore ti lascia spingere il numero di righe fino a cinquecento, cambiare palette per residuo e attraversare ogni primo da 2 a 23.",
  ctaLabel: "→ Apri l'Esploratore",
};

const pt: RichStory = {
  page: {
    pretitle: "Tema · Geometria",
    title: "O triângulo de Pascal (mod n)",
    tagline: "Colore por divisibilidade — sai um fractal.",
    intro:
      "O triângulo de Pascal é a tabela dos coeficientes binomiais C(n, k). Cada entrada é a soma das duas de cima. Reduz módulo um primo e o padrão de cor que sobra é um fractal perfeito e infinito. A razão esconde-se na aritmética em base p.",
    ctaInteractive: "→ Abrir o Explorador",
  },
  encounter: {
    pretitle: "Primeiro encontro",
    title: "Escreve um triângulo de números. Colore os ímpares. Vê chegar um fractal.",
    cards: [
      {
        label: "01",
        title: "A ideia central",
        body: "Empilha os coeficientes binomiais C(n, k) num triângulo: 1 no topo, depois 1 1, depois 1 2 1, e assim por diante, cada entrada é a soma das duas de cima. Fica só com o resto módulo um primo p. A imagem que sobra é fractal, exata, infinita.",
      },
      {
        label: "02",
        title: "Um exemplo concreto",
        body: "Toma p = 2. Marca cada entrada ímpar, deixa em branco as pares. Recua. Estás a ver o triângulo de Sierpiński — não uma aproximação, o verdadeiro, gerado por puro contar. Três cópias autossemelhantes em cada escala, para sempre.",
      },
      {
        label: "03",
        title: "Porque importa",
        body: "Kummer provou em 1852 que a potência de p que divide C(n, k) é o número de transportes ao somar k + (n−k) em base p. Logo o fractal é um retrato de quando a soma em base p é limpa — geometria escondida na aritmética.",
      },
    ],
    tryIt:
      "Abaixo: desliza o módulo e o número de linhas, e deixa uma única coluna de somas decidir cada cor.",
  },
  sections: [
    {
      pretitle: "Secção 01 · O triângulo em si",
      title: "C(n, k) — a regra de contagem mais simples",
      body: "Escreve 1 no topo. Debaixo, cada entrada é a soma das duas de cima. As linhas — 1 · 1 1 · 1 2 1 · 1 3 3 1 · 1 4 6 4 1 — são os coeficientes binomiais C(n, k), que contam de quantas formas se escolhem k objetos de n. Não é preciso mais para construir um fractal.",
    },
    {
      pretitle: "Secção 02 · Colore por resto",
      title: "Mod 2 é Sierpiński, exatamente",
      body: "Troca cada entrada pelo seu resto módulo 2 e colore só as ímpares. Recua e a imagem é o triângulo de Sierpiński — o peneiro autossemelhante exato, até ao fundo. Qualquer bloco de 2^k linhas são três cópias do bloco 2^(k−1) em triângulo, com o centro vazio.",
    },
    {
      pretitle: "Secção 03 · Teorema de Kummer (1852)",
      title: "Divisibilidade = número de transportes",
      body: "Porque é que mod p se fatoriza tão limpo? O teorema de Kummer diz: a maior potência de p que divide C(n, k) é o número de transportes ao somar k e (n − k) em base p. Logo C(n, k) ≢ 0 mod p exatamente quando não há transporte — quando cada dígito em base p de k fica ≤ ao dígito correspondente de n. O fractal é o retrato da soma sem transporte.",
    },
    {
      pretitle: "Secção 04 · Outros primos, outros peneiros",
      title: "Mod 3, mod 5, mod 7 — cada um o seu peneiro autossemelhante",
      body: "Muda p para 3 e a mesma regra dá um triângulo de cópias três-por-três; p = 5 dá um micro-azulejo de quinze peças; p = 7 um de vinte e oito. O teorema de Lucas (1878) torna-o explícito: C(n, k) mod p fatoriza-se em produto de C(nᵢ, kᵢ) mod p sobre os dígitos em base p. Outro primo, outro fractal — mesma engrenagem.",
    },
    {
      pretitle: "Secção 05 · Dimensões de Hausdorff",
      title: "log((p+1)p/2) / log p, a subir para 2",
      body: "O peneiro mod p tem dimensão de Hausdorff log((p+1)p/2) / log p. Para p = 2 dá log 3 / log 2 ≈ 1,585; para p = 3 cerca de 1,631; para p = 7 já 1,771. Crescendo p, a dimensão sobe para 2 — o triângulo enche cada vez mais o plano, mas nunca tudo.",
    },
    {
      pretitle: "Secção 06 · Módulos não primos",
      title: "n composto: o fractal continua, mas borrado",
      body: "Reduz mod 6 e a contagem limpa de Kummer parte-se: a estrutura por potências primas embaraça-se. A imagem fica autossemelhante em grande — o teorema chinês dos restos empilha os padrões mod 2 e mod 3 — mas a simetria local desfia. Stephen Wolfram catalogou estas no NKS como os autómatas celulares mais próximos de Pascal mod p.",
    },
  ],
  viewer: {
    caption: "Interativo · triângulo de Pascal mod p",
    modulusLabel: "Módulo p",
    rowsLabel: "Linhas N",
    primesOnlyLabel: "Só primos",
    includeCompositesLabel: "Incluir compostos",
    pretitle: "Interativo · a imagem",
    title: "Desliza o módulo, conta o peneiro",
    body: "Escolhe um primo e o render encaixa num peneiro fractal limpo; liga compostos e a simetria amolece. Sobe N até 256 linhas para ver autossimilaridade mais funda.",
  },
  carry: {
    caption: "Interativo · contador de transportes de Kummer",
    nLabel: "n",
    kLabel: "k",
    pLabel: "primo p",
    resultLabel: "Valor de Lucas",
    carryLabel: "Transportes (≥ 1 ⇒ divisível)",
    noCarryLabel: "Transportes (0 ⇒ não nulo mod p)",
    hint: "Zero transportes significa que C(n, k) é não nulo mod p — uma célula colorida do peneiro. Qualquer transporte manda C(n, k) a 0 mod p — célula vazia.",
    pretitle: "Interativo · a regra por trás da cor",
    title: "Soma k + (n − k) em base p e vê o transporte decidir",
    body: "Escreve n e k. Escolhe um primo. A vista empilha os dígitos em base p de k e (n − k); as colunas que transportam brilham em âmbar. Zero transportes ⇒ célula colorida. Um transporte ⇒ célula vazia.",
  },
  dimensionLabel: "Dimensão de Hausdorff",
  dimensionNote:
    "Estritamente entre uma curva (1) e uma região (2). Crescendo p o peneiro enche-se mais — o limite é 2, nunca atingido.",
  closingPretitle: "Vai mais longe",
  closingTitle: "Abre o Explorador.",
  closingBody:
    "O Explorador deixa-te empurrar o número de linhas até quinhentas, alternar paletas por resíduo e percorrer cada primo de 2 a 23.",
  ctaLabel: "→ Abrir o Explorador",
};

const sv: RichStory = {
  page: {
    pretitle: "Ämne · Geometri",
    title: "Pascals triangel (mod n)",
    tagline: "Färga efter delbarhet — en fraktal faller ut.",
    intro:
      "Pascals triangel är uppslagsverket för binomialkoefficienterna C(n, k). Varje post är summan av de två ovanför. Reducera modulo ett primtal och färgmönstret som blir kvar är en perfekt, oändlig fraktal. Skälet gömmer sig i bas-p-aritmetik.",
    ctaInteractive: "→ Öppna Utforskaren",
  },
  encounter: {
    pretitle: "Första mötet",
    title: "Skriv en triangel av tal. Färga de udda. Se en fraktal komma fram.",
    cards: [
      {
        label: "01",
        title: "Den stora idén",
        body: "Stapla binomialkoefficienterna C(n, k) i en triangel: 1 högst upp, sedan 1 1, sedan 1 2 1, och så vidare, varje post är summan av de två ovanför. Behåll bara resten modulo ett primtal p. Bilden som finns kvar är fraktal, exakt, oändlig.",
      },
      {
        label: "02",
        title: "Ett konkret exempel",
        body: "Ta p = 2. Markera varje udda post, lämna varje jämn tom. Backa. Du tittar på Sierpiński-triangeln — inte en approximation, den äkta varan, alstrad av rent räknande. Tre självlika kopior i varje skala, för alltid.",
      },
      {
        label: "03",
        title: "Varför det betyder något",
        body: "Kummer bevisade 1852 att potensen av p som delar C(n, k) är antalet minnessiffror när k + (n−k) adderas i bas p. Så fraktalen är ett porträtt av när bas-p-addition är minnesfri — geometri gömd i aritmetik.",
      },
    ],
    tryIt:
      "Nedan: dra modulen och antalet rader, låt sedan en enda kolumn av additioner avgöra varje färg.",
  },
  sections: [
    {
      pretitle: "Avsnitt 01 · Själva triangeln",
      title: "C(n, k) — den enklaste räkneregeln på jorden",
      body: "Skriv 1 högst upp. Under är varje post summan av de två ovanför. Raderna — 1 · 1 1 · 1 2 1 · 1 3 3 1 · 1 4 6 4 1 — är binomialkoefficienterna C(n, k) och räknar på hur många sätt man väljer k saker av n. Mer behövs inte för att bygga en fraktal.",
    },
    {
      pretitle: "Avsnitt 02 · Färga efter rest",
      title: "Mod 2 är Sierpiński, exakt",
      body: "Ersätt varje post med dess rest modulo 2 och färga bara de udda. Backa och bilden är Sierpiński-triangeln — den exakta självlika silen, hela vägen ned. Varje 2^k-radersblock är tre kopior av 2^(k−1)-blocket i triangelform, med ihåligt centrum.",
    },
    {
      pretitle: "Avsnitt 03 · Kummers sats (1852)",
      title: "Delbarhet = antal minnessiffror",
      body: "Varför faktoriseras mod p så rent? Kummers sats säger: den högsta potensen av p som delar C(n, k) är antalet minnessiffror när k och (n − k) adderas i bas p. Alltså C(n, k) ≢ 0 mod p just när ingen minnessiffra uppstår — när varje bas-p-siffra i k förblir ≤ motsvarande siffra i n. Fraktalen är porträttet av minnesfri addition.",
    },
    {
      pretitle: "Avsnitt 04 · Andra primtal, andra silar",
      title: "Mod 3, mod 5, mod 7 — var och en sin självlika sil",
      body: "Byt p till 3 och samma regel ger en triangel av tre-gånger-tre-kopior; p = 5 ger en mikroplatta med femton bitar; p = 7 en med tjugoåtta. Lucas sats (1878) gör det explicit: C(n, k) mod p faktoriseras till produkten av C(nᵢ, kᵢ) mod p över bas-p-siffrorna. Annat primtal, annan fraktal — samma maskineri.",
    },
    {
      pretitle: "Avsnitt 05 · Hausdorffdimensioner",
      title: "log((p+1)p/2) / log p, klättrandes mot 2",
      body: "Mod-p-silen har Hausdorffdimension log((p+1)p/2) / log p. För p = 2 ger det log 3 / log 2 ≈ 1,585; för p = 3 ungefär 1,631; för p = 7 redan 1,771. När p växer kryper dimensionen mot 2 — triangeln fyller mer och mer av planet, men aldrig allt.",
    },
    {
      pretitle: "Avsnitt 06 · Icke-prima moduler",
      title: "Sammansatt n: fraktalen finns kvar, men suddig",
      body: "Reducera mod 6 och Kummers rena minnessiffereräkning bryts: primpotensstrukturen trasslar sig. Bilden förblir självlik i stort — kinesiska restsatsen staplar mönstren mod 2 och mod 3 — men lokal symmetri fransar ut. Stephen Wolfram katalogiserade dessa i NKS som de cellulära automater som ligger närmast Pascal mod p.",
    },
  ],
  viewer: {
    caption: "Interaktivt · Pascals triangel mod p",
    modulusLabel: "Modul p",
    rowsLabel: "Rader N",
    primesOnlyLabel: "Endast primtal",
    includeCompositesLabel: "Inkludera sammansatta",
    pretitle: "Interaktivt · bilden",
    title: "Dra modulen, räkna silen",
    body: "Välj ett primtal och renderingen snäpper till en ren fraktalsil; slå på sammansatta och symmetrin mjuknar. Skruva upp N till 256 rader för djupare självlikhet.",
  },
  carry: {
    caption: "Interaktivt · Kummers minnessiffereräknare",
    nLabel: "n",
    kLabel: "k",
    pLabel: "primtal p",
    resultLabel: "Lucas-värde",
    carryLabel: "Minnessiffror (≥ 1 ⇒ delbart)",
    noCarryLabel: "Minnessiffror (0 ⇒ inte noll mod p)",
    hint: "Noll minnessiffror betyder att C(n, k) inte är noll mod p — en färgad cell i silen. Vilken minnessiffra som helst skickar C(n, k) till 0 mod p — tom cell.",
    pretitle: "Interaktivt · regeln bakom färgen",
    title: "Addera k + (n − k) i bas p och se minnessiffran avgöra",
    body: "Skriv ett n och ett k. Välj ett primtal. Vyn staplar bas-p-siffrorna i k och (n − k); kolumner som ger minnessiffra glöder bärnsten. Noll minnessiffror ⇒ färgad cell. En minnessiffra ⇒ tom cell.",
  },
  dimensionLabel: "Hausdorffdimension",
  dimensionNote:
    "Strikt mellan en kurva (1) och en yta (2). När p växer fylls silen mer — gränsen är 2, aldrig nådd.",
  closingPretitle: "Gå vidare",
  closingTitle: "Öppna Utforskaren.",
  closingBody:
    "Utforskaren låter dig pressa antalet rader till ett halvt tusen, byta palett per rest och stega genom varje primtal från 2 till 23.",
  ctaLabel: "→ Öppna Utforskaren",
};

const no: RichStory = {
  page: {
    pretitle: "Tema · Geometri",
    title: "Pascals trekant (mod n)",
    tagline: "Fargelegg etter delelighet — en fraktal faller ut.",
    intro:
      "Pascals trekant er oppslagstabellen for binomialkoeffisientene C(n, k). Hver oppføring er summen av de to over. Reduser modulo et primtall, og fargemønsteret som står igjen er en perfekt, uendelig fraktal. Grunnen gjemmer seg i base-p-aritmetikk.",
    ctaInteractive: "→ Åpne Utforskeren",
  },
  encounter: {
    pretitle: "Første møte",
    title: "Skriv en trekant av tall. Fargelegg de oddetallene. Se en fraktal komme fram.",
    cards: [
      {
        label: "01",
        title: "Den store ideen",
        body: "Stable binomialkoeffisientene C(n, k) i en trekant: 1 på toppen, så 1 1, så 1 2 1, og videre, hver oppføring er summen av de to over. Behold bare resten modulo et primtall p. Bildet som står igjen er fraktalt, eksakt, uendelig.",
      },
      {
        label: "02",
        title: "Et konkret eksempel",
        body: "Ta p = 2. Marker hver oddetallsoppføring, la hver partalls være tom. Tre tilbake. Du ser på Sierpiński-trekanten — ikke en tilnærming, den ekte varen, laget av ren telling. Tre selvlike kopier på hver skala, for alltid.",
      },
      {
        label: "03",
        title: "Hvorfor det betyr noe",
        body: "Kummer beviste i 1852 at potensen av p som deler C(n, k) er antall mente når k + (n−k) legges sammen i base p. Så fraktalen er et portrett av når base-p-addisjon er menteløs — geometri gjemt i aritmetikk.",
      },
    ],
    tryIt:
      "Under: dra modulen og radantallet, og la én enkelt kolonne av addisjoner avgjøre hver farge.",
  },
  sections: [
    {
      pretitle: "Avsnitt 01 · Selve trekanten",
      title: "C(n, k) — den enkleste telleregelen på jorden",
      body: "Skriv 1 på toppen. Under er hver oppføring summen av de to over. Radene — 1 · 1 1 · 1 2 1 · 1 3 3 1 · 1 4 6 4 1 — er binomialkoeffisientene C(n, k) og teller hvor mange måter å velge k ting av n. Mer trengs ikke for å bygge en fraktal.",
    },
    {
      pretitle: "Avsnitt 02 · Fargelegg etter rest",
      title: "Mod 2 er Sierpiński, eksakt",
      body: "Bytt ut hver oppføring med resten modulo 2 og fargelegg bare de oddetallene. Tre tilbake og bildet er Sierpiński-trekanten — den eksakte selvlike silen, hele veien ned. Hver 2^k-rad-blokk er tre kopier av 2^(k−1)-blokken i trekantform, med hult senter.",
    },
    {
      pretitle: "Avsnitt 03 · Kummers teorem (1852)",
      title: "Delelighet = antall mente",
      body: "Hvorfor faktoriserer mod p så rent? Kummers teorem sier: den høyeste potensen av p som deler C(n, k) er antall mente når k og (n − k) legges sammen i base p. Altså C(n, k) ≢ 0 mod p akkurat når det ikke oppstår noen mente — når hvert base-p-siffer i k blir ≤ tilsvarende siffer i n. Fraktalen er portrettet av menteløs addisjon.",
    },
    {
      pretitle: "Avsnitt 04 · Andre primtall, andre siler",
      title: "Mod 3, mod 5, mod 7 — hver sin selvlike sil",
      body: "Bytt p til 3 og samme regel gir en trekant av tre-ganger-tre-kopier; p = 5 gir en mikrofliser med femten biter; p = 7 en med tjueåtte. Lucas' teorem (1878) gjør det eksplisitt: C(n, k) mod p faktoriserer som produktet av C(nᵢ, kᵢ) mod p over base-p-sifrene. Annet primtall, annen fraktal — samme maskineri.",
    },
    {
      pretitle: "Avsnitt 05 · Hausdorff-dimensjoner",
      title: "log((p+1)p/2) / log p, klatrende mot 2",
      body: "Mod-p-silen har Hausdorff-dimensjon log((p+1)p/2) / log p. For p = 2 gir det log 3 / log 2 ≈ 1,585; for p = 3 omtrent 1,631; for p = 7 allerede 1,771. Når p vokser, kryper dimensjonen mot 2 — trekanten fyller mer og mer av planet, men aldri alt.",
    },
    {
      pretitle: "Avsnitt 06 · Ikke-prime moduler",
      title: "Sammensatt n: fraktalen er der ennå, men uskarp",
      body: "Reduser mod 6 og Kummers rene mentetelling brister: primpotensstrukturen vikler seg. Bildet forblir selvlikt i stort — kinesisk restteorem stabler mønstrene mod 2 og mod 3 — men lokal symmetri rakner. Stephen Wolfram katalogiserte disse i NKS som de cellulære automatene nærmest Pascal mod p.",
    },
  ],
  viewer: {
    caption: "Interaktivt · Pascals trekant mod p",
    modulusLabel: "Modulus p",
    rowsLabel: "Rader N",
    primesOnlyLabel: "Kun primtall",
    includeCompositesLabel: "Inkluder sammensatte",
    pretitle: "Interaktivt · bildet",
    title: "Dra modulen, tell silen",
    body: "Velg et primtall og rendringen klikker inn til en ren fraktalsil; slå på sammensatte og symmetrien mykner. Skru N opp til 256 rader for å se dypere selvlikhet.",
  },
  carry: {
    caption: "Interaktivt · Kummers mente-teller",
    nLabel: "n",
    kLabel: "k",
    pLabel: "primtall p",
    resultLabel: "Lucas-verdi",
    carryLabel: "Mente (≥ 1 ⇒ delelig)",
    noCarryLabel: "Mente (0 ⇒ ikke null mod p)",
    hint: "Null mente betyr at C(n, k) ikke er null mod p — en farget celle i silen. Enhver mente sender C(n, k) til 0 mod p — tom celle.",
    pretitle: "Interaktivt · regelen bak fargen",
    title: "Legg sammen k + (n − k) i base p og se menten avgjøre",
    body: "Skriv inn n og k. Velg et primtall. Visningen stabler base-p-sifrene i k og (n − k); kolonner med mente lyser rav. Null mente ⇒ farget celle. En mente ⇒ tom celle.",
  },
  dimensionLabel: "Hausdorff-dimensjon",
  dimensionNote:
    "Strengt mellom en kurve (1) og en flate (2). Når p vokser fyller silen mer — grensen er 2, aldri nådd.",
  closingPretitle: "Gå videre",
  closingTitle: "Åpne Utforskeren.",
  closingBody:
    "Utforskeren lar deg presse radantallet til et halvt tusen, bytte palett per rest og stege gjennom hvert primtall fra 2 til 23.",
  ctaLabel: "→ Åpne Utforskeren",
};

const RICH_STORY: Record<Locale, RichStory> = { en, de, es, fr, it, pt, sv, no };

// --------------------------------------------------------------------------

export default function PascalmodStory() {
  const { locale } = useI18n();
  const story = RICH_STORY[locale];
  // The shared StoryPage shape includes a `sections` array that the shell
  // never reads; we render our own sections below.
  const page: StoryPage = { ...story.page, sections: [] };
  const [sec0, sec1, sec2, sec3, sec4, sec5] = story.sections;

  return (
    <StoryPageShell
      page={page}
      ctaHref="/pascalmod/explorer"
      accent={ACCENT}
      borderAccent="border-signal-amber/70"
      bgAccent="bg-signal-amber/10"
      hoverAccent="hover:bg-signal-amber/20"
      gradient="from-signal-amber/10"
      formulaBadge="C(n, k) mod p ≠ 0  ⇔  no carry in base-p addition of k + (n−k)"
      formulaLatex={"\\binom{n}{k} \\not\\equiv 0 \\pmod{p} \\iff \\text{no carry in base-}p"}
      formulaSize="sm"
      finalLabel={story.closingTitle}
    >
      {/* Encounter — three approachable cards */}
      <section className="mx-auto mb-32 max-w-5xl space-y-10">
        <div className="space-y-3 text-center">
          <Reveal>
            <div className={`font-mono text-[10px] uppercase tracking-widest2 ${ACCENT}`}>
              {story.encounter.pretitle}
            </div>
          </Reveal>
          <Reveal delay={100}>
            <h2 className="math-italic text-4xl leading-tight md:text-5xl">
              {story.encounter.title}
            </h2>
          </Reveal>
        </div>
        <div className="grid grid-cols-1 gap-5 md:grid-cols-3">
          {story.encounter.cards.map((card, i) => (
            <Reveal key={card.label} delay={120 + i * 100}>
              <article className="glass hairline h-full space-y-3 rounded-2xl border p-6 transition-colors hover:border-signal-amber/40">
                <div className={`font-mono text-[10px] uppercase tracking-widest2 ${ACCENT}`}>
                  {card.label}
                </div>
                <h3 className="math-italic text-2xl leading-snug text-ink-100">{card.title}</h3>
                <p className="text-sm leading-relaxed text-ink-200">{card.body}</p>
              </article>
            </Reveal>
          ))}
        </div>
        <Reveal delay={500}>
          <div className="text-center italic text-ink-300">{story.encounter.tryIt}</div>
        </Reveal>
      </section>

      {/* Section 01 — the triangle itself */}
      <section className="mx-auto mb-32 max-w-4xl space-y-6">
        <StoryCard {...sec0!} accent={ACCENT} />
      </section>

      {/* Section 02 — colour by remainder */}
      <section className="mx-auto mb-32 max-w-4xl space-y-6">
        <StoryCard {...sec1!} accent={ACCENT} />
      </section>

      {/* INTERACTIVE 1 · Pascal viewer */}
      <section className="mx-auto mb-32 max-w-5xl space-y-6">
        <Reveal>
          <div className="space-y-2 text-center">
            <div className={`font-mono text-[10px] uppercase tracking-widest2 ${ACCENT}`}>
              {story.viewer.pretitle}
            </div>
            <h2 className="math-italic text-3xl leading-tight md:text-4xl">{story.viewer.title}</h2>
            <p className="mx-auto max-w-2xl text-sm leading-relaxed text-ink-200">
              {story.viewer.body}
            </p>
          </div>
        </Reveal>
        <Reveal delay={120}>
          <PascalmodViewer
            caption={story.viewer.caption}
            modulusLabel={story.viewer.modulusLabel}
            rowsLabel={story.viewer.rowsLabel}
            primesOnlyLabel={story.viewer.primesOnlyLabel}
            includeCompositesLabel={story.viewer.includeCompositesLabel}
          />
        </Reveal>
      </section>

      {/* Section 03 — Kummer's theorem */}
      <section className="mx-auto mb-32 max-w-4xl space-y-6">
        <StoryCard {...sec2!} accent={ACCENT} />
        <Reveal delay={120}>
          <div className="hairline space-y-3 rounded-2xl border bg-ink-950/40 p-8 text-center">
            <div className={`font-mono text-[10px] uppercase tracking-widest2 ${ACCENT}`}>
              Kummer, 1852
            </div>
            <div className="math-italic text-xl leading-tight text-ink-100 md:text-2xl">
              v_p(C(n, k)) = # carries when k + (n − k) is added in base p
            </div>
          </div>
        </Reveal>
      </section>

      {/* INTERACTIVE 2 · Carry demo */}
      <section className="mx-auto mb-32 max-w-5xl space-y-6">
        <Reveal>
          <div className="space-y-2 text-center">
            <div className={`font-mono text-[10px] uppercase tracking-widest2 ${ACCENT}`}>
              {story.carry.pretitle}
            </div>
            <h2 className="math-italic text-3xl leading-tight md:text-4xl">{story.carry.title}</h2>
            <p className="mx-auto max-w-2xl text-sm leading-relaxed text-ink-200">
              {story.carry.body}
            </p>
          </div>
        </Reveal>
        <Reveal delay={120}>
          <PascalmodCarryDemo
            caption={story.carry.caption}
            nLabel={story.carry.nLabel}
            kLabel={story.carry.kLabel}
            pLabel={story.carry.pLabel}
            resultLabel={story.carry.resultLabel}
            carryLabel={story.carry.carryLabel}
            noCarryLabel={story.carry.noCarryLabel}
            hint={story.carry.hint}
          />
        </Reveal>
      </section>

      {/* Section 04 — other primes */}
      <section className="mx-auto mb-32 max-w-4xl space-y-6">
        <StoryCard {...sec3!} accent={ACCENT} />
      </section>

      {/* Section 05 — Hausdorff dimensions */}
      <section className="mx-auto mb-32 max-w-4xl space-y-6">
        <StoryCard {...sec4!} accent={ACCENT} />
        <Reveal delay={120}>
          <div className="hairline space-y-4 rounded-2xl border bg-ink-950/40 p-8">
            <div className={`font-mono text-[10px] uppercase tracking-widest2 ${ACCENT}`}>
              {story.dimensionLabel}
            </div>
            <div className="math-italic text-center text-2xl leading-tight text-ink-100 md:text-3xl">
              dim_H = log((p+1)p/2) / log p
            </div>
            <div className="grid grid-cols-2 gap-3 pt-2 md:grid-cols-4">
              {[
                { p: 2, d: "1.585" },
                { p: 3, d: "1.631" },
                { p: 5, d: "1.683" },
                { p: 7, d: "1.771" },
              ].map(({ p, d }) => (
                <div
                  key={p}
                  className="hairline space-y-1 rounded-md border bg-ink-950/60 p-3 text-center"
                >
                  <div className="font-mono text-[10px] uppercase tracking-widest2 text-ink-300">
                    p = {p}
                  </div>
                  <div className="font-mono text-lg text-signal-amber">≈ {d}</div>
                </div>
              ))}
            </div>
            <p className="text-xs leading-relaxed text-ink-400">{story.dimensionNote}</p>
          </div>
        </Reveal>
      </section>

      {/* Section 06 — non-prime moduli */}
      <section className="mx-auto mb-32 max-w-4xl space-y-6">
        <StoryCard {...sec5!} accent={ACCENT} />
      </section>

      {/* Closing CTA */}
      <Reveal>
        <section className="glass hairline mx-auto mb-16 max-w-3xl space-y-6 rounded-3xl border p-10 text-center">
          <div className={`font-mono text-[10px] uppercase tracking-widest2 ${ACCENT}`}>
            {story.closingPretitle}
          </div>
          <div className="math-italic shimmer-text text-3xl leading-tight md:text-5xl">
            {story.closingTitle}
          </div>
          <p className="leading-relaxed text-ink-200">{story.closingBody}</p>
          <Link
            href="/pascalmod/explorer"
            className="inline-block rounded-full border border-signal-amber/70 bg-signal-amber/10 px-8 py-4 font-mono text-sm uppercase tracking-widest2 text-signal-amber transition-colors hover:bg-signal-amber/25"
          >
            {story.ctaLabel}
          </Link>
        </section>
      </Reveal>
    </StoryPageShell>
  );
}
