// Route inventory for the sitemap. Generated from the app/ directory on
// 2026-09-05; extend it when a topic gains a new interactive sub-room.
import type { TopicId } from "@/lib/topics";

export const TOPIC_SUBROUTES: Partial<Record<TopicId, readonly string[]>> = {
  aizawa: ["explorer"],
  apollonian: ["explorer"],
  backprop: ["explorer"],
  banach: ["explorer"],
  boids: ["explorer"],
  buffon: ["explorer"],
  bzr: ["explorer"],
  cantor: ["explorer"],
  cardioid: ["explorer"],
  chaosgame: ["explorer"],
  collatz: ["explorer"],
  diffusion: ["explorer"],
  dla: ["explorer"],
  doublependulum: ["explorer"],
  euler: ["explorer"],
  eulerchar: ["explorer"],
  fourcolor: ["explorer"],
  fourier: ["explorer", "sound"],
  gabrielshorn: ["explorer"],
  galton: ["explorer"],
  godel: ["explorer"],
  halting: ["explorer"],
  hilberthotel: ["explorer"],
  iota: ["reducer"],
  konigsberg: ["explorer"],
  langton: ["explorer"],
  life: ["sandbox"],
  logistic: ["explorer", "sound"],
  lorenz: ["explorer"],
  lsystem: ["explorer"],
  magpendulum: ["explorer"],
  mandelbrot: ["explorer"],
  mobius: ["explorer"],
  nand: ["builder"],
  pascalmod: ["explorer"],
  penrose: ["explorer"],
  phi: ["explorer"],
  pvsnp: ["explorer"],
  riemann: ["explorer"],
  rsa: ["explorer"],
  rule110: ["simulator"],
  sat: ["explorer"],
  sierpinski: ["explorer"],
  smallworld: ["explorer"],
  sternbrocot: ["explorer"],
  turingpattern: ["explorer"],
  ulam: ["explorer"],
  wang: ["explorer"],
} as const;

export const STATIC_PAGES = ["/about", "/impressum", "/datenschutz"] as const;
