"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { useI18n } from "@/lib/i18n/context";
import { useDpr } from "@/lib/hooks/useDpr";
import { palette } from "@/lib/visual/palette";
import type { Locale } from "@/lib/i18n/types";

// Generator indices: 0 = a, 1 = a⁻¹, 2 = b, 3 = b⁻¹.
// Inverse pairing — index i and INV[i] cancel one another, so a node never
// branches back along the direction it just came from (otherwise we'd have a
// non-reduced word).
const INV = [1, 0, 3, 2] as const;

// Cardinal directions for each generator. The Cayley graph of F₂ is the
// infinite 4-valent tree; we draw it in the plane by giving each generator
// one of the four compass directions.
const DIRS: ReadonlyArray<{ dx: number; dy: number }> = [
  { dx: 1, dy: 0 }, // a → right
  { dx: -1, dy: 0 }, // a⁻¹ → left
  { dx: 0, dy: -1 }, // b → up
  { dx: 0, dy: 1 }, // b⁻¹ → down
];

const GEN_LABELS = ["a", "a⁻¹", "b", "b⁻¹"] as const;
const GEN_COLORS = [
  "rgb(255, 122, 182)", // rose       — a
  "rgb(196, 124, 255)", // violet     — a⁻¹
  "rgb(125, 243, 255)", // cyan       — b
  "rgb(255, 209, 102)", // amber      — b⁻¹
] as const;

const ROOT_LEN = 150;
const SHRINK = 0.5;

// --------------------------------------------------------------------------
// Per-locale strings for this explorer. Kept inline so the multi-locale
// prose lives next to the explorer it serves and doesn't fatten the shared
// i18n bundles.
// --------------------------------------------------------------------------

type RichExplorer = {
  cayleyBadge: string;
  paradoxBadge: string;
  canvasFooter: string;
  depthLabel: string;
  depthUnit: string;
  highlightLabel: string;
  highlightHint: string;
  wordsStartingWith: (label: string) => string;
  showTheTrick: string;
  whatYouSeeLabel: string;
  whatYouSeeP1: string;
  whatYouSeeP2: string;
  overlayMsg: (highlightLabel: string, inverseLabel: string) => string;
  overlaySubMsg: string;
};

const EXPLORER: Record<Locale, RichExplorer> = {
  en: {
    cayleyBadge: "Cayley tree · F₂ = ⟨a, b⟩",
    paradoxBadge: "B³ = B³ ⊔ B³",
    canvasFooter: "Each node = one reduced word · colour = first letter",
    depthLabel: "Tree depth",
    depthUnit: "levels",
    highlightLabel: "Highlight a piece",
    highlightHint:
      "Each toggle picks one of the four paradoxical pieces — all words whose first letter is that generator.",
    wordsStartingWith: (label) => `words starting with ${label}`,
    showTheTrick: "Show the trick",
    whatYouSeeLabel: "What you are seeing",
    whatYouSeeP1:
      "The infinite tree is the Cayley graph of the free group F₂ generated by two rotations a and b. Every reduced word in a, a⁻¹, b, b⁻¹ is a different node; the root is the identity rotation. Each non-root node has three children (it can't go back via the inverse of the step that produced it).",
    whatYouSeeP2:
      "Colour each node by the first letter of its word and you split F₂ into four disjoint pieces W(a), W(a⁻¹), W(b), W(b⁻¹). The paradox is purely combinatorial: multiplying W(a⁻¹) on the left by a (its inverse) covers every word that doesn't start with a — i.e. the three other pieces plus the identity. One piece, shifted, is three pieces plus a point. Lift this from the group to the sphere via Hausdorff (1914), then to the ball — and one ball becomes two.",
    overlayMsg: (h, inv) => `W(${h}) shifted by ${inv} covers F₂ ∖ W(${inv})`,
    overlaySubMsg: "this piece, multiplied by its inverse generator, equals the whole tree",
  },
  de: {
    cayleyBadge: "Cayley-Baum · F₂ = ⟨a, b⟩",
    paradoxBadge: "B³ = B³ ⊔ B³",
    canvasFooter: "Jeder Knoten = ein reduziertes Wort · Farbe = Anfangsbuchstabe",
    depthLabel: "Baumtiefe",
    depthUnit: "Ebenen",
    highlightLabel: "Stück hervorheben",
    highlightHint:
      "Jede Auswahl wählt eines der vier paradoxen Stücke — alle Wörter, die mit diesem Erzeuger beginnen.",
    wordsStartingWith: (label) => `Wörter, die mit ${label} beginnen`,
    showTheTrick: "Den Trick zeigen",
    whatYouSeeLabel: "Was du siehst",
    whatYouSeeP1:
      "Der unendliche Baum ist der Cayley-Graph der freien Gruppe F₂, erzeugt von zwei Drehungen a und b. Jedes reduzierte Wort in a, a⁻¹, b, b⁻¹ ist ein eigener Knoten; die Wurzel ist die identische Drehung. Jeder Nicht-Wurzel-Knoten hat drei Kinder (er kann nicht über das Inverse seines letzten Schritts zurückgehen).",
    whatYouSeeP2:
      "Färbe jeden Knoten nach dem Anfangsbuchstaben seines Wortes — und du zerlegst F₂ in vier disjunkte Stücke W(a), W(a⁻¹), W(b), W(b⁻¹). Das Paradox ist rein kombinatorisch: Multiplikation von W(a⁻¹) von links mit a (dem Inversen) überdeckt jedes Wort, das nicht mit a beginnt — also die drei anderen Stücke plus die Identität. Ein Stück, einmal verschoben, ergibt drei Stücke plus einen Punkt. Hebe das via Hausdorff (1914) von der Gruppe auf die Sphäre, dann auf die Kugel — und aus einer Kugel werden zwei.",
    overlayMsg: (h, inv) => `W(${h}) verschoben um ${inv} überdeckt F₂ ∖ W(${inv})`,
    overlaySubMsg:
      "dieses Stück, mit seinem inversen Erzeuger multipliziert, ergibt den ganzen Baum",
  },
  es: {
    cayleyBadge: "Árbol de Cayley · F₂ = ⟨a, b⟩",
    paradoxBadge: "B³ = B³ ⊔ B³",
    canvasFooter: "Cada nodo = una palabra reducida · color = primera letra",
    depthLabel: "Profundidad del árbol",
    depthUnit: "niveles",
    highlightLabel: "Resaltar una pieza",
    highlightHint:
      "Cada interruptor escoge una de las cuatro piezas paradójicas — todas las palabras cuya primera letra es ese generador.",
    wordsStartingWith: (label) => `palabras que empiezan por ${label}`,
    showTheTrick: "Mostrar el truco",
    whatYouSeeLabel: "Lo que estás viendo",
    whatYouSeeP1:
      "El árbol infinito es el grafo de Cayley del grupo libre F₂ generado por dos rotaciones a y b. Cada palabra reducida en a, a⁻¹, b, b⁻¹ es un nodo distinto; la raíz es la rotación identidad. Cada nodo que no es raíz tiene tres hijos (no puede volver por el inverso del paso que lo produjo).",
    whatYouSeeP2:
      "Colorea cada nodo según la primera letra de su palabra y divides F₂ en cuatro piezas disjuntas W(a), W(a⁻¹), W(b), W(b⁻¹). La paradoja es puramente combinatoria: multiplicar W(a⁻¹) por la izquierda por a (su inverso) cubre toda palabra que no empieza por a — es decir, las otras tres piezas más la identidad. Una pieza, desplazada, son tres piezas más un punto. Lleva esto del grupo a la esfera vía Hausdorff (1914), luego a la bola — y una bola se vuelve dos.",
    overlayMsg: (h, inv) => `W(${h}) desplazada por ${inv} cubre F₂ ∖ W(${inv})`,
    overlaySubMsg: "esta pieza, multiplicada por su generador inverso, es todo el árbol",
  },
  fr: {
    cayleyBadge: "Arbre de Cayley · F₂ = ⟨a, b⟩",
    paradoxBadge: "B³ = B³ ⊔ B³",
    canvasFooter: "Chaque nœud = un mot réduit · couleur = première lettre",
    depthLabel: "Profondeur de l'arbre",
    depthUnit: "niveaux",
    highlightLabel: "Mettre une pièce en évidence",
    highlightHint:
      "Chaque bouton choisit l'une des quatre pièces paradoxales — tous les mots dont la première lettre est ce générateur.",
    wordsStartingWith: (label) => `mots commençant par ${label}`,
    showTheTrick: "Montrer le tour",
    whatYouSeeLabel: "Ce que tu vois",
    whatYouSeeP1:
      "L'arbre infini est le graphe de Cayley du groupe libre F₂ engendré par deux rotations a et b. Chaque mot réduit en a, a⁻¹, b, b⁻¹ est un nœud distinct ; la racine est la rotation identité. Chaque nœud non-racine a trois enfants (il ne peut pas revenir par l'inverse du pas qui l'a produit).",
    whatYouSeeP2:
      "Colore chaque nœud selon la première lettre de son mot et tu sépares F₂ en quatre pièces disjointes W(a), W(a⁻¹), W(b), W(b⁻¹). Le paradoxe est purement combinatoire : multiplier W(a⁻¹) à gauche par a (son inverse) recouvre tout mot qui ne commence pas par a — c'est-à-dire les trois autres pièces plus l'identité. Une pièce, décalée, vaut trois pièces plus un point. Remonte cela du groupe à la sphère via Hausdorff (1914), puis à la boule — et une boule en devient deux.",
    overlayMsg: (h, inv) => `W(${h}) décalée de ${inv} recouvre F₂ ∖ W(${inv})`,
    overlaySubMsg: "cette pièce, multipliée par son générateur inverse, vaut l'arbre entier",
  },
  it: {
    cayleyBadge: "Albero di Cayley · F₂ = ⟨a, b⟩",
    paradoxBadge: "B³ = B³ ⊔ B³",
    canvasFooter: "Ogni nodo = una parola ridotta · colore = prima lettera",
    depthLabel: "Profondità dell'albero",
    depthUnit: "livelli",
    highlightLabel: "Evidenzia un pezzo",
    highlightHint:
      "Ogni interruttore sceglie uno dei quattro pezzi paradossali — tutte le parole la cui prima lettera è quel generatore.",
    wordsStartingWith: (label) => `parole che iniziano con ${label}`,
    showTheTrick: "Mostra il trucco",
    whatYouSeeLabel: "Ciò che stai vedendo",
    whatYouSeeP1:
      "L'albero infinito è il grafo di Cayley del gruppo libero F₂ generato da due rotazioni a e b. Ogni parola ridotta in a, a⁻¹, b, b⁻¹ è un nodo distinto; la radice è la rotazione identità. Ogni nodo non-radice ha tre figli (non può tornare indietro tramite l'inverso del passo che l'ha prodotto).",
    whatYouSeeP2:
      "Colora ogni nodo in base alla prima lettera della sua parola e dividi F₂ in quattro pezzi disgiunti W(a), W(a⁻¹), W(b), W(b⁻¹). Il paradosso è puramente combinatorio: moltiplicare W(a⁻¹) a sinistra per a (il suo inverso) copre ogni parola che non inizia con a — cioè gli altri tre pezzi più l'identità. Un pezzo, traslato, sono tre pezzi più un punto. Solleva tutto questo dal gruppo alla sfera via Hausdorff (1914), poi alla palla — e una palla diventa due.",
    overlayMsg: (h, inv) => `W(${h}) traslato di ${inv} copre F₂ ∖ W(${inv})`,
    overlaySubMsg: "questo pezzo, moltiplicato per il suo generatore inverso, è l'intero albero",
  },
  pt: {
    cayleyBadge: "Árvore de Cayley · F₂ = ⟨a, b⟩",
    paradoxBadge: "B³ = B³ ⊔ B³",
    canvasFooter: "Cada nó = uma palavra reduzida · cor = primeira letra",
    depthLabel: "Profundidade da árvore",
    depthUnit: "níveis",
    highlightLabel: "Destacar uma peça",
    highlightHint:
      "Cada botão escolhe uma das quatro peças paradoxais — todas as palavras cuja primeira letra é esse gerador.",
    wordsStartingWith: (label) => `palavras que começam por ${label}`,
    showTheTrick: "Mostrar o truque",
    whatYouSeeLabel: "O que estás a ver",
    whatYouSeeP1:
      "A árvore infinita é o grafo de Cayley do grupo livre F₂ gerado por duas rotações a e b. Cada palavra reduzida em a, a⁻¹, b, b⁻¹ é um nó distinto; a raiz é a rotação identidade. Cada nó não-raiz tem três filhos (não pode voltar pelo inverso do passo que o produziu).",
    whatYouSeeP2:
      "Pinta cada nó pela primeira letra da sua palavra e divides F₂ em quatro peças disjuntas W(a), W(a⁻¹), W(b), W(b⁻¹). O paradoxo é puramente combinatório: multiplicar W(a⁻¹) à esquerda por a (o seu inverso) cobre toda palavra que não começa por a — isto é, as outras três peças mais a identidade. Uma peça, deslocada, são três peças mais um ponto. Sobe isto do grupo para a esfera via Hausdorff (1914), depois para a bola — e uma bola torna-se duas.",
    overlayMsg: (h, inv) => `W(${h}) deslocada por ${inv} cobre F₂ ∖ W(${inv})`,
    overlaySubMsg: "esta peça, multiplicada pelo seu gerador inverso, é a árvore inteira",
  },
  sv: {
    cayleyBadge: "Cayley-träd · F₂ = ⟨a, b⟩",
    paradoxBadge: "B³ = B³ ⊔ B³",
    canvasFooter: "Varje nod = ett reducerat ord · färg = första bokstaven",
    depthLabel: "Träddjup",
    depthUnit: "nivåer",
    highlightLabel: "Markera en bit",
    highlightHint:
      "Varje växel väljer en av de fyra paradoxala bitarna — alla ord vars första bokstav är den generatorn.",
    wordsStartingWith: (label) => `ord som börjar med ${label}`,
    showTheTrick: "Visa tricket",
    whatYouSeeLabel: "Det du ser",
    whatYouSeeP1:
      "Det oändliga trädet är Cayley-grafen av den fria gruppen F₂ som genereras av två rotationer a och b. Varje reducerat ord i a, a⁻¹, b, b⁻¹ är en egen nod; roten är identitetsrotationen. Varje icke-rotnod har tre barn (den kan inte gå tillbaka via inversen av steget som producerade den).",
    whatYouSeeP2:
      "Färga varje nod efter första bokstaven i dess ord och du delar F₂ i fyra disjunkta bitar W(a), W(a⁻¹), W(b), W(b⁻¹). Paradoxen är rent kombinatorisk: att multiplicera W(a⁻¹) från vänster med a (dess invers) täcker varje ord som inte börjar med a — alltså de tre andra bitarna plus identiteten. En bit, förskjuten, är tre bitar plus en punkt. Lyft detta från gruppen till sfären via Hausdorff (1914), sedan till klotet — och ett klot blir två.",
    overlayMsg: (h, inv) => `W(${h}) förskjuten med ${inv} täcker F₂ ∖ W(${inv})`,
    overlaySubMsg: "denna bit, multiplicerad med sin inversa generator, är hela trädet",
  },
  no: {
    cayleyBadge: "Cayley-tre · F₂ = ⟨a, b⟩",
    paradoxBadge: "B³ = B³ ⊔ B³",
    canvasFooter: "Hver node = ett redusert ord · farge = første bokstav",
    depthLabel: "Tredybde",
    depthUnit: "nivåer",
    highlightLabel: "Marker en bit",
    highlightHint:
      "Hver bryter velger en av de fire paradoksale bitene — alle ord der første bokstav er den generatoren.",
    wordsStartingWith: (label) => `ord som starter med ${label}`,
    showTheTrick: "Vis trikset",
    whatYouSeeLabel: "Det du ser",
    whatYouSeeP1:
      "Det uendelige treet er Cayley-grafen til den frie gruppen F₂ generert av to rotasjoner a og b. Hvert reduserte ord i a, a⁻¹, b, b⁻¹ er en egen node; roten er identitetsrotasjonen. Hver ikke-rot-node har tre barn (den kan ikke gå tilbake via inversen av skrittet som produserte den).",
    whatYouSeeP2:
      "Fargelegg hver node etter første bokstav i dens ord, og du splitter F₂ i fire disjunkte biter W(a), W(a⁻¹), W(b), W(b⁻¹). Paradokset er rent kombinatorisk: å multiplisere W(a⁻¹) fra venstre med a (dens invers) dekker hvert ord som ikke begynner med a — altså de tre andre bitene pluss identiteten. Én bit, forskjøvet, er tre biter pluss et punkt. Løft dette fra gruppen til sfæren via Hausdorff (1914), så til kulen — og én kule blir til to.",
    overlayMsg: (h, inv) => `W(${h}) forskjøvet med ${inv} dekker F₂ ∖ W(${inv})`,
    overlaySubMsg: "denne biten, multiplisert med sin inverse generator, er hele treet",
  },
};

export default function BanachExplorer() {
  const { a, u, locale } = useI18n();
  // banach is registered in atlas — pull the localised topic copy.
  const topic = a.topics.banach;
  const x = EXPLORER[locale];

  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const dpr = useDpr();
  const [depth, setDepth] = useState(5);
  const [highlight, setHighlight] = useState<number | null>(null);
  const [shift, setShift] = useState(0); // 0..1 animation progress for "the trick"
  const shiftRaf = useRef<number | null>(null);

  // Trigger the shift animation
  const playTheTrick = () => {
    if (highlight === null) return;
    if (shiftRaf.current !== null) cancelAnimationFrame(shiftRaf.current);
    const start = performance.now();
    const DURATION = 1400;
    const tick = (now: number) => {
      const p = Math.min(1, (now - start) / DURATION);
      // ease in-out
      const eased = p < 0.5 ? 2 * p * p : 1 - Math.pow(-2 * p + 2, 2) / 2;
      setShift(eased);
      if (p < 1) {
        shiftRaf.current = requestAnimationFrame(tick);
      } else {
        shiftRaf.current = null;
      }
    };
    shiftRaf.current = requestAnimationFrame(tick);
  };

  useEffect(() => {
    return () => {
      if (shiftRaf.current !== null) cancelAnimationFrame(shiftRaf.current);
    };
  }, []);

  // When the highlight selection changes, reset the shift animation.
  useEffect(() => {
    if (shiftRaf.current !== null) {
      cancelAnimationFrame(shiftRaf.current);
      shiftRaf.current = null;
    }
    setShift(0);
  }, [highlight]);

  // Render the Cayley tree
  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const render = () => {
      const W = canvas.clientWidth;
      const H = canvas.clientHeight;
      canvas.width = Math.floor(W * dpr);
      canvas.height = Math.floor(H * dpr);
      const ctx = canvas.getContext("2d");
      if (!ctx) return;
      ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

      // Background
      ctx.fillStyle = palette.canvas.bg;
      ctx.fillRect(0, 0, W, H);

      // Faint background grid
      ctx.strokeStyle = "rgba(138,144,164,0.07)";
      ctx.lineWidth = 1;
      for (let i = 0; i <= 12; i++) {
        const xg = (i / 12) * W;
        const yg = (i / 12) * H;
        ctx.beginPath();
        ctx.moveTo(xg, 0);
        ctx.lineTo(xg, H);
        ctx.stroke();
        ctx.beginPath();
        ctx.moveTo(0, yg);
        ctx.lineTo(W, yg);
        ctx.stroke();
      }

      const cx = W / 2;
      const cy = H / 2;

      // Collect every (parent → child) segment along with the first-letter
      // class so we can colour by piece without rerunning the recursion.
      interface Seg {
        x1: number;
        y1: number;
        x2: number;
        y2: number;
        first: number; // root letter (the piece this node belongs to)
        depth: number;
      }
      const segs: Seg[] = [];
      const nodes: Array<{ x: number; y: number; first: number; depth: number }> = [];

      const walk = (
        px: number,
        py: number,
        prevDir: number | null,
        first: number | null,
        len: number,
        d: number,
      ) => {
        if (d >= depth) return;
        for (let i = 0; i < 4; i++) {
          if (prevDir !== null && i === INV[prevDir]) continue;
          const dir = DIRS[i];
          const nx = px + dir.dx * len;
          const ny = py + dir.dy * len;
          const firstLetter = first === null ? i : first;
          segs.push({ x1: px, y1: py, x2: nx, y2: ny, first: firstLetter, depth: d });
          nodes.push({ x: nx, y: ny, first: firstLetter, depth: d + 1 });
          walk(nx, ny, i, firstLetter, len * SHRINK, d + 1);
        }
      };

      walk(0, 0, null, null, ROOT_LEN, 0);

      // When "the trick" plays, the highlighted piece slides toward the
      // origin: visually, W(g) shifted by g⁻¹ swallows the rest of the tree.
      const shiftDir = highlight !== null ? DIRS[INV[highlight]] : { dx: 0, dy: 0 };
      const shiftX = shiftDir.dx * ROOT_LEN * shift;
      const shiftY = shiftDir.dy * ROOT_LEN * shift;

      const colorFor = (first: number, isHighlighted: boolean): string => {
        if (highlight === null) return GEN_COLORS[first];
        if (isHighlighted) return GEN_COLORS[first];
        // Dim non-matching pieces
        return "rgba(138,144,164,0.18)";
      };

      // Draw segments
      ctx.lineWidth = 1.2;
      for (const s of segs) {
        const isH = highlight === null ? false : s.first === highlight;
        ctx.strokeStyle = colorFor(s.first, isH);
        const ox = isH ? shiftX : 0;
        const oy = isH ? shiftY : 0;
        ctx.beginPath();
        ctx.moveTo(cx + s.x1 + ox, cy + s.y1 + oy);
        ctx.lineTo(cx + s.x2 + ox, cy + s.y2 + oy);
        ctx.stroke();
      }

      // Draw nodes
      for (const n of nodes) {
        const isH = highlight === null ? false : n.first === highlight;
        ctx.fillStyle = colorFor(n.first, isH);
        const ox = isH ? shiftX : 0;
        const oy = isH ? shiftY : 0;
        const r = Math.max(1.2, 4 - n.depth * 0.45);
        ctx.beginPath();
        ctx.arc(cx + n.x + ox, cy + n.y + oy, r, 0, Math.PI * 2);
        ctx.fill();
      }

      // Identity (root)
      ctx.fillStyle = "#fff";
      ctx.beginPath();
      ctx.arc(cx, cy, 5, 0, Math.PI * 2);
      ctx.fill();
      ctx.font = "10px ui-monospace, monospace";
      ctx.fillStyle = "rgba(255,255,255,0.7)";
      ctx.fillText("e", cx + 8, cy - 6);

      // Generator labels at the four root-children positions
      ctx.font = "11px ui-monospace, monospace";
      for (let i = 0; i < 4; i++) {
        const d = DIRS[i];
        const lx = cx + d.dx * (ROOT_LEN + 18) - 6;
        const ly = cy + d.dy * (ROOT_LEN + 18) + 4;
        ctx.fillStyle = GEN_COLORS[i];
        ctx.fillText(GEN_LABELS[i], lx, ly);
      }

      // Overlay text when the trick is playing
      if (highlight !== null && shift > 0.02) {
        ctx.fillStyle = "rgba(6,7,13,0.78)";
        ctx.fillRect(0, H - 56, W, 56);
        ctx.fillStyle = "#fff";
        ctx.font = "12px ui-monospace, monospace";
        ctx.fillText(x.overlayMsg(GEN_LABELS[highlight], GEN_LABELS[INV[highlight]]), 16, H - 32);
        ctx.fillStyle = "rgba(255,255,255,0.55)";
        ctx.fillText(x.overlaySubMsg, 16, H - 14);
      }
    };

    render();
    const ro = new ResizeObserver(render);
    ro.observe(canvas);
    return () => ro.disconnect();
  }, [depth, dpr, highlight, shift, x]);

  return (
    <main className="flex min-h-screen flex-col pt-14">
      <div className="grid flex-1 grid-cols-1 gap-0 lg:grid-cols-[1fr_420px]">
        <div className="relative flex min-h-[60vh] flex-col gap-4 bg-ink-950 p-4 lg:min-h-[calc(100vh-3.5rem)] lg:p-6">
          <div className="flex items-center justify-between gap-3">
            <div className="glass hairline rounded-md border px-3 py-2 font-mono text-[10px] uppercase tracking-widest2 text-ink-200">
              {x.cayleyBadge}
            </div>
            <div className="glass hairline rounded-md border px-3 py-2 font-mono text-[10px] uppercase tracking-widest2 text-signal-rose">
              {x.paradoxBadge}
            </div>
          </div>
          <div className="hairline flex-1 overflow-hidden rounded-2xl border bg-ink-950">
            <canvas ref={canvasRef} className="block h-full w-full" />
          </div>
          <div className="glass hairline rounded-md border px-3 py-2 font-mono text-[10px] uppercase tracking-widest2 text-ink-200">
            {x.canvasFooter}
          </div>
        </div>

        <aside className="hairline scrollbar-thin flex flex-col overflow-y-auto border-l bg-ink-900/40">
          <div className="hairline space-y-3 border-b p-6">
            <div className="font-mono text-[10px] uppercase tracking-widest2 text-signal-rose">
              {topic.title}
            </div>
            <h1 className="math-italic text-3xl leading-tight text-ink-100">{topic.tagline}</h1>
            <p className="text-sm leading-relaxed text-ink-200">{topic.body}</p>
          </div>

          <div className="hairline space-y-4 border-b p-5">
            <div className="font-mono text-[10px] uppercase tracking-widest2 text-ink-300">
              {x.depthLabel}
            </div>
            <div className="flex items-center justify-between font-mono text-sm">
              <span className="text-signal-rose">{depth}</span>
              <span className="text-[10px] text-ink-400">{x.depthUnit}</span>
            </div>
            <input
              type="range"
              value={depth}
              min={1}
              max={7}
              step={1}
              onChange={(e) => setDepth(parseInt(e.target.value, 10))}
              className="w-full accent-signal-rose"
            />
          </div>

          <div className="hairline space-y-4 border-b p-5">
            <div className="font-mono text-[10px] uppercase tracking-widest2 text-ink-300">
              {x.highlightLabel}
            </div>
            <p className="text-[11px] leading-relaxed text-ink-400">{x.highlightHint}</p>
            <div className="grid grid-cols-2 gap-2">
              {GEN_LABELS.map((label, i) => {
                const active = highlight === i;
                return (
                  <button
                    key={label}
                    onClick={() => setHighlight(active ? null : i)}
                    className={`rounded-md border px-3 py-2 text-left font-mono transition-colors ${
                      active
                        ? "border-signal-rose/60 bg-signal-rose/10"
                        : "hairline text-ink-200 hover:border-signal-rose/40 hover:text-ink-100"
                    }`}
                    style={active ? { color: GEN_COLORS[i] } : undefined}
                  >
                    <div className="text-sm" style={{ color: GEN_COLORS[i] }}>
                      W({label})
                    </div>
                    <div className="mt-0.5 text-[10px] text-ink-400">
                      {x.wordsStartingWith(label)}
                    </div>
                  </button>
                );
              })}
            </div>
            <button
              onClick={playTheTrick}
              disabled={highlight === null}
              className={`w-full rounded-md border px-3 py-2 font-mono text-[10px] uppercase tracking-widest2 transition-colors ${
                highlight === null
                  ? "cursor-not-allowed border-ink-700/40 text-ink-500"
                  : "border-signal-rose/60 bg-signal-rose/10 text-signal-rose hover:bg-signal-rose/20"
              }`}
            >
              {x.showTheTrick}
            </button>
          </div>

          <div className="hairline space-y-3 border-b p-5">
            <div className="font-mono text-[10px] uppercase tracking-widest2 text-ink-300">
              {x.whatYouSeeLabel}
            </div>
            <p className="text-[12px] leading-relaxed text-ink-200">{x.whatYouSeeP1}</p>
            <p className="text-[12px] leading-relaxed text-ink-200">{x.whatYouSeeP2}</p>
          </div>

          <div className="p-5">
            <Link
              href="/"
              className="hairline block w-full rounded-md border py-2 text-center font-mono text-[10px] uppercase tracking-widest2 text-ink-300 transition-colors hover:border-signal-rose/40 hover:text-signal-rose"
            >
              {u.back}
            </Link>
          </div>
        </aside>
      </div>
    </main>
  );
}
